-- ========================================
-- users table
-- ========================================

CREATE TABLE users (
                       user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(50) NOT NULL UNIQUE,
                       password_hash VARCHAR(255) NOT NULL
);


-- ========================================
-- tasks table
-- ========================================

CREATE TABLE tasks (
                       task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       user_id BIGINT NOT NULL,
                       title VARCHAR(100) NOT NULL,
                       status VARCHAR(20) NOT NULL,
                       description VARCHAR(1000),

                       CONSTRAINT fk_tasks_users
                           FOREIGN KEY (user_id)
                               REFERENCES users(user_id)
);